### ISSUE TITLE
[Well-Architected Partners - 100 Lab] - Cloud9 environment instance type too small for current version of Amplify

### ISSUE THREAD

**Issue by carlos-aws** [awslabs/aws-well-architected-labs#593]
**Lab**: Well-Architected Partners - Level 100: Automating Serverless Best Practices with Dashbird

**Issue Description**:
During the [Deploy The Blue Car Application](https://www.wellarchitectedlabs.com/well-architectedpartners/100_labs/100_automating_serverless_best_practices_with_dashbird/1_deploy_blue_car_application/) step, the build script ``build_script.sh`` that is ran from the Cloud9 environment fails to initialize Amplify with below error:
```
Downloading release from https://package.cli.amplify.aws/9.0.0/amplify-pkg-linux-x64.tgz
node:internal/buffer:959
    super(bufferOrLength, byteOffset, length);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at createUnsafeBuffer (node:internal/buffer:1062:12)
    at allocate (node:buffer:410:10)
    at Function.allocUnsafe (node:buffer:375:10)
    at Function.concat (node:buffer:553:25)
    at Extract.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@aws-amplify/cli/lib/binary.js:127:37)
    at Extract.emit (node:events:539:35)
    at finishMaybe (/home/ec2-user/.nvm/versions/node/v16.15.1/lib/node_modules/@aws-amplify/cli/node_modules/readable-stream/lib/_stream_writable.js:624:14)
```

From the error, "Array buffer allocation failed", this is happening due to memory exhaustion on the instance. As per my tests this is happening since amplify-cli version 8.0.2 and above.

**Suggested fix:**
This problem can be avoided by using an environment with more memory. Current setup uses a Cloud9 environment with instance type ``t2.micro (1vCPU 1GiB)``. By using a bigger instance type, such as ``t3.small (2vCPU 2GiB)``, this memory allocation issues does not happen and amplify is initialized properly by the build script.

Changing the CloudFormation template [section1-oncall-health-sample-app.yaml](https://www.wellarchitectedlabs.com/wapartners/100_Automating_Serverless_Best_Practices_with_Dashbird/Code/templates/section1/section1-oncall-health-sample-app.yaml) referenced in the lab to use ``InstanceType: 't3.small'`` for Cloud9 (instead of t2.micro) solves this.

**Comment by sssalim-aws** [comment]
Change Merged
